#!/usr/bin/env python3
"""Project reviewed runtime policy into Swift resources, Steam UI and launcher."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
START = '# BEGIN GENERATED RUNTIME POLICY'
END = '# END GENERATED RUNTIME POLICY'


def outputs():
    source = (ROOT / 'runtime/policy.json').read_text()
    policy = json.loads(source)
    if policy['schemaVersion'] != 1:
        raise ValueError('Unknown runtime policy schema')
    tools = {}
    shell = [START, '# Generated by runtime/generate-policy.py; edit runtime/policy.json.',
             'np_runtime_policy() {', '  NP_POLICY_KNOWN=0', '  case "$1" in']
    for identity, runtime in policy['runtimes'].items():
        if not re.fullmatch('[A-Za-z0-9_.-]+', identity) or runtime['automatic'] not in ['dxmt', 'dxvk', 'wined3d']:
            raise ValueError('Invalid policy identity or automatic renderer')
        for key, state in runtime['capabilities'].items():
            if key != 'automatic' and state not in ['supported', 'experimental', 'unavailable']:
                raise ValueError('Invalid capability state')
        for tool in runtime['tools']:
            if not re.fullmatch('[A-Za-z0-9_.-]+', tool) or tool in tools:
                raise ValueError('Invalid or duplicate tool policy')
            tools[tool] = dict(runtime, id=identity)
        shell.extend([f'    {identity})', '      NP_POLICY_KNOWN=1', f'      NP_AUTOMATIC_BACKEND={runtime["automatic"]}'])
        for key, state in runtime['capabilities'].items():
            if key not in ['automatic', 'fex']:
                shell.append(f'      NP_CAP_{key.upper()}={state}')
        shell.append('      ;;')
    shell += ['  esac', '}', 'np_validate_options() {']
    for key, option in policy['options'].items():
        if not re.fullmatch('[A-Z0-9_]+', key) or not re.fullmatch('[a-z0-9]+', option['feature']):
            raise ValueError('Invalid option policy')
        allowed = '|'.join(option['renderers']) or '__unavailable__'
        label = option['label']
        if not re.fullmatch('[A-Za-z0-9 ]+', label):
            raise ValueError('Invalid option label')
        shell += [f'  case "${{{key}:-}}" in', "    ''|0) ;;", '    *)',
                  f'      if [ "${{NP_CAP_{option["feature"].upper()}:-unavailable}}" = unavailable ]; then',
                  f'        unsupported_feature="{label}"', '      fi',
                  '      case "$NP_EFFECTIVE_BACKEND" in', f'        {allowed}) ;;',
                  f'        *) unsupported_feature="{label}" ;;', '      esac', '      ;;', '  esac']
    shell += ['}', END]
    launcher = ROOT / 'dylib/feats/compat_run.sh'
    text = launcher.read_text()
    block = '\n'.join(shell)
    if START in text:
        text = re.sub(re.escape(START) + '.*?' + re.escape(END), lambda _: block, text, flags=re.S)
    else:
        index = text.index('\n') + 1
        text = text[:index] + '\n' + block + '\n' + text[index:]
    javascript = json.dumps(tools, separators=(',', ':'))
    return {
        ROOT / 'app/Sources/NotProtonApp/Resources/runtime-policy.json': source,
        ROOT / 'dylib/feats/runtime_policy.h': '// Generated by runtime/generate-policy.py.\n#pragma once\n#define NP_RUNTIME_POLICIES ' + json.dumps(javascript) + '\n#define NP_RUNTIME_OPTIONS ' + json.dumps(json.dumps(policy['options'], separators=(',', ':'))) + '\n',
        launcher: text,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for file, value in outputs().items():
        if args.check:
            if not file.exists() or file.read_text() != value:
                raise ValueError('Stale runtime policy projection: ' + str(file.relative_to(ROOT)))
        else:
            file.write_text(value)


if __name__ == '__main__':
    main()
