#!/usr/bin/env python3
"""Project the reviewed profile catalog into the app/helper and Steam panel."""
import argparse
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def outputs():
    source = json.loads((ROOT / 'runtime/game-profiles.json').read_text())
    assert source['schemaVersion'] == 1
    policies = json.loads((ROOT / 'runtime/policy.json').read_text())['runtimes']
    seen = set()
    for profile in source['profiles']:
        assert profile['id'] not in seen
        seen.add(profile['id'])
        assert profile['revision'] >= 1 and profile['appID'].isdigit()
        assert profile['executable'].endswith('.exe') and '/' not in profile['executable'] and '\\' not in profile['executable']
        assert set(profile['runtimes']) <= policies.keys()
        assert set(profile['renderers']) <= {'dxmt', 'dxvk'}
        assert profile['architectures'] == ['x86_64']
        assert set(profile['defaults']) <= {'dxgi.customVendorId', 'dxgi.customDeviceId'}
        assert all(len(value) == 4 and all(char in '0123456789abcdef' for char in value) for value in profile['defaults'].values())
        assert not profile['recipes']  # No real failing dependency case is qualified yet.
    assert source['recipes'] == []
    encoded = base64.b64encode(json.dumps(source, sort_keys=True).encode()).decode()
    javascript = json.dumps(source['profiles'], separators=(',', ':'))
    return {
        ROOT / 'app/Sources/NotProtonApp/Model/GameProfileCatalog.swift':
            '// Generated by runtime/generate-profiles.py.\nimport Foundation\n'
            'enum GameProfileCatalog { static let data = Data(base64Encoded: "' + encoded + '")! }\n',
        ROOT / 'dylib/feats/game_profiles.h': '// Generated by runtime/generate-profiles.py.\n#pragma once\n#define NP_GAME_PROFILES ' + json.dumps(javascript) + '\n',
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit('Stale profile projection: ' + str(path))
        else:
            path.write_text(content)


if __name__ == '__main__':
    main()
